import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Playfair_Display } from 'next/font/google'; // Example heading font
import { Pacifico } from 'next/font/google'; // Example decorative font
import './globals.css';

// Body font (Geist)
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});

// Mono font
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

// Heading font
const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-heading',
});

// Decorative font
const pacifico = Pacifico({
	weight: '400',
	subsets: ['latin'],
	variable: '--font-decorative',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${pacifico.variable} font-sans antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
